# Generated by Django 6.0.5 on 2026-06-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_remove_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='01818474582', max_length=11),
            preserve_default=False,
        ),
    ]
