# Generated by Django 6.0.5 on 2026-05-25 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_district', to='django_app.district'),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='blood_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donor_blood_group', to='django_app.bloodgroup'),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donor_district', to='django_app.district'),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='donor_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='upazila',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donor_upazila', to='django_app.upazila'),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='upazila',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_upazila', to='django_app.upazila'),
        ),
    ]
