# Generated by Django 6.0.5 on 2026-07-27 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='donor_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='upazila',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donor_upazila', to='django_app.upazila'),
        ),
    ]
