# Generated by Django 6.0.5 on 2026-08-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorprofile',
            name='district',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='upazila',
            field=models.CharField(max_length=15),
        ),
        migrations.RemoveField(
            model_name='donorprofile',
            name='full_address',
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='village',
            field=models.CharField(default='v', max_length=30),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='Upazila',
        ),
    ]
