# Generated by Django 6.0.5 on 2026-05-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='total_donations',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
