# Generated by Django 6.0.5 on 2026-06-03 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0003_donorprofile_total_donations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorprofile',
            name='phone',
        ),
    ]
