# Generated by Django 6.0.5 on 2026-06-06 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0004_remove_donorprofile_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloodrequest',
            old_name='created_by',
            new_name='user',
        ),
    ]
