# Generated by Django 6.0.5 on 2026-06-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0005_rename_created_by_bloodrequest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='hospital_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='patient_name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='upazila',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
